# Имя приложения по умолчанию
appName: my-service

# Кол-во копий запустить
replicaCount: 1

# Образ контейнера
image:
  # Путь к образу в GitHub Registry
  repository: ghcr.io/csu-itmo-2025-2/team3-booking-system/booking-service
  # Тег образа (последняя версия)
  tag: latest
  # Проверка наличия новой версии
  pullPolicy: Always

# Порт, на котором работает приложение внутри контейнера
service:
  port: 80
  targetPort: 8000

# Лимит ресурсов
resources:
  requests:
    cpu: 50m    # 0.05 CPU 
    memory: 64Mi
  limits:
    cpu: 100m   # 0.1 CPU
    memory: 128Mi

# Переменные окружения (для настроек БД)
env: {}

# Секреты (для паролей)
secrets: {}